//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrutasVerdurasDeshidratadas.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FrutasyVegetalesDeshidratadosEntities : DbContext
    {
        public FrutasyVegetalesDeshidratadosEntities()
            : base("name=FrutasyVegetalesDeshidratadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_CartStatus> Tbl_CartStatus { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Distribuidor> Tbl_Distribuidor { get; set; }
        public virtual DbSet<Tbl_MemberRole> Tbl_MemberRole { get; set; }
        public virtual DbSet<Tbl_Members> Tbl_Members { get; set; }
        public virtual DbSet<Tbl_Order> Tbl_Order { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_ShippingDetails> Tbl_ShippingDetails { get; set; }
        public virtual DbSet<Tbl_ShoppingCart> Tbl_ShoppingCart { get; set; }
        public virtual DbSet<Tbl_Status_Distribuidor> Tbl_Status_Distribuidor { get; set; }
        public virtual DbSet<Tbl_Contacto> Tbl_Contacto { get; set; }
        public virtual DbSet<Tbl_Partners> Tbl_Partners { get; set; }
        public virtual DbSet<Tbl_PayPal_Config> Tbl_PayPal_Config { get; set; }
        public virtual DbSet<Tbl_System_Config> Tbl_System_Config { get; set; }
    
        public virtual ObjectResult<USP_Get_Elements_From_ShoppingCart_By_ID_Result> USP_Get_Elements_From_ShoppingCart_By_ID(Nullable<int> p_ProductId)
        {
            var p_ProductIdParameter = p_ProductId.HasValue ?
                new ObjectParameter("p_ProductId", p_ProductId) :
                new ObjectParameter("p_ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Elements_From_ShoppingCart_By_ID_Result>("USP_Get_Elements_From_ShoppingCart_By_ID", p_ProductIdParameter);
        }
    
        public virtual ObjectResult<USP_Get_Elements_To_ShoppingCart_Result> USP_Get_Elements_To_ShoppingCart(Nullable<int> p_memberId)
        {
            var p_memberIdParameter = p_memberId.HasValue ?
                new ObjectParameter("p_memberId", p_memberId) :
                new ObjectParameter("p_memberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Elements_To_ShoppingCart_Result>("USP_Get_Elements_To_ShoppingCart", p_memberIdParameter);
        }
    
        public virtual int USP_Get_Order_Details(Nullable<int> p_MemberID)
        {
            var p_MemberIDParameter = p_MemberID.HasValue ?
                new ObjectParameter("p_MemberID", p_MemberID) :
                new ObjectParameter("p_MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Get_Order_Details", p_MemberIDParameter);
        }
    
        public virtual ObjectResult<USP_Get_Products_Result> USP_Get_Products(Nullable<int> p_IdCategory)
        {
            var p_IdCategoryParameter = p_IdCategory.HasValue ?
                new ObjectParameter("p_IdCategory", p_IdCategory) :
                new ObjectParameter("p_IdCategory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Get_Products_Result>("USP_Get_Products", p_IdCategoryParameter);
        }
    
        public virtual ObjectResult<USP_Proceed_To_Pay_Result> USP_Proceed_To_Pay(Nullable<int> p_MemberID)
        {
            var p_MemberIDParameter = p_MemberID.HasValue ?
                new ObjectParameter("p_MemberID", p_MemberID) :
                new ObjectParameter("p_MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Proceed_To_Pay_Result>("USP_Proceed_To_Pay", p_MemberIDParameter);
        }
    
        public virtual ObjectResult<USP_Search_Result> USP_Search(string searchKey)
        {
            var searchKeyParameter = searchKey != null ?
                new ObjectParameter("searchKey", searchKey) :
                new ObjectParameter("searchKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Search_Result>("USP_Search", searchKeyParameter);
        }
    
        public virtual ObjectResult<USP_ShowOrderCompleted_Result> USP_ShowOrderCompleted(Nullable<int> p_MemberID, string p_TransaccionID)
        {
            var p_MemberIDParameter = p_MemberID.HasValue ?
                new ObjectParameter("p_MemberID", p_MemberID) :
                new ObjectParameter("p_MemberID", typeof(int));
    
            var p_TransaccionIDParameter = p_TransaccionID != null ?
                new ObjectParameter("p_TransaccionID", p_TransaccionID) :
                new ObjectParameter("p_TransaccionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ShowOrderCompleted_Result>("USP_ShowOrderCompleted", p_MemberIDParameter, p_TransaccionIDParameter);
        }
    }
}
