//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrutasVerdurasDeshidratadas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Distribuidor
    {
        public int Id_Distribuidor { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public int Id_EstatusDist { get; set; }
        public string Estado { get; set; }
        public string Ciudad_Municipio { get; set; }
        public string Nombres { get; set; }
        public string CalleNumero { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> CP { get; set; }
        public string Telefono { get; set; }
        public string eMail { get; set; }
        public bool EsProspecto { get; set; }
        public string FolioSolicitud { get; set; }
    
        public virtual Tbl_Status_Distribuidor Tbl_Status_Distribuidor { get; set; }
    }
}
