//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrutasVerdurasDeshidratadas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Partners()
        {
            this.Tbl_PayPal_Config = new HashSet<Tbl_PayPal_Config>();
            this.Tbl_System_Config = new HashSet<Tbl_System_Config>();
        }
    
        public int Id_Parner { get; set; }
        public string Description { get; set; }
        public string eMail { get; set; }
        public string AddressLine1 { get; set; }
        public string Estate { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PayPal_Config> Tbl_PayPal_Config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_System_Config> Tbl_System_Config { get; set; }
    }
}
