//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrutasVerdurasDeshidratadas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ShoppingCart
    {
        public int Id_ShoppingCart { get; set; }
        public int ProductId { get; set; }
        public int MemberId { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CartStatusId { get; set; }
        public Nullable<int> ShippingDetailId { get; set; }
    
        public virtual Tbl_CartStatus Tbl_CartStatus { get; set; }
        public virtual Tbl_Members Tbl_Members { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_ShippingDetails Tbl_ShippingDetails { get; set; }
    }
}
