//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrutasVerdurasDeshidratadas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_System_Config
    {
        public int Id_SystemConfig { get; set; }
        public int Id_Parner { get; set; }
        public string SMTP { get; set; }
        public int PORT { get; set; }
        public string Sender { get; set; }
        public string PswSender { get; set; }
        public string SOReceiver { get; set; }
    
        public virtual Tbl_Partners Tbl_Partners { get; set; }
    }
}
