//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrutasVerdurasDeshidratadas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public int OrderId { get; set; }
        public decimal AmountPaid { get; set; }
        public string TransactionID { get; set; }
        public int NumberOfPieces { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> OrderPlacedDate { get; set; }
    }
}
