//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrutasVerdurasDeshidratadas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contacto
    {
        public int Id_Contacto { get; set; }
        public string eMail { get; set; }
        public string TextoMensaje { get; set; }
        public System.DateTime FechaContacto { get; set; }
    }
}
